### ISSUE TITLE
too large local residue for mass conservation

### ISSUE THREAD

**Issue by jdonners** [PhysicsofFluids/AFiD#7]
R wrote:
* test on 384^3 using  ./configure FCFLAGS="-O3 -xAVX -axCORE-AVX2”. afid-1.1 crashes on an Ivy Bridge node (i.e. AVX) with the message “too large local residue for mass conservation at:”. This code works fine on a Haswell node (i.e. AVX2).
* Using only the “-O3” flag everything works well on both types of nodes.
* Using the “-O3 -xAVX” flags the code fails on both types of nodes, so the problem is in the part “-xAVX”.

It also occurs with the latest compiler version (16.0.1). 

some print statements show:
```
...
16:  dmax,resid=  6.953275390687991E-310  1.000000000000000E-002
18:  dmax,resid=  6.952658331733957E-310  1.000000000000000E-002
00:  dmax,resid= -1.797693134862316E+308  1.000000000000000E-002
00:           too large local residue for mass conservation at:
```
only process 0 has a somewhat excessive residue..

the same happens with ./configure FCFLAGS="-xAVX -O0 -g -traceback", so without optimization.

**Comment by stevensrjam** [comment]
Wether the code crashes depends also on the simulation case that is configured. For 192^3 the code works also on the Ivy Bridge nodes. This problem is probably related to the one we saw for the GPU version, see Github change https://github.com/PhysicsofFluids/AFiD_GPU/commit/49dde1f3c53ac9465a107c074407ad879fd6b541



On Jan 25, 2016, at 22:38, maxcuda <notifications@github.com<mailto:notifications@github.com>> wrote:


R wrote:

  *   test on 384^3 using ./configure FCFLAGS="-O3 -xAVX -axCORE-AVX2”. afid-1.1 crashes on an Ivy Bridge node (i.e. AVX) with the message “too large local residue for mass conservation at:”. This code works fine on a Haswell node (i.e. AVX2).
  *   Using only the “-O3” flag everything works well on both types of nodes.
  *   Using the “-O3 -xAVX” flags the code fails on both types of nodes, so the problem is in the part “-xAVX”.

It also occurs with the latest compiler version (16.0.1).

some print statements show:

...
16:  dmax,resid=  6.953275390687991E-310  1.000000000000000E-002
18:  dmax,resid=  6.952658331733957E-310  1.000000000000000E-002
00:  dmax,resid= -1.797693134862316E+308  1.000000000000000E-002
00:           too large local residue for mass conservation at:


only process 0 has a somewhat excessive residue..

the same happens with ./configure FCFLAGS="-xAVX -O0 -g -traceback", so without optimization.

**Comment by jdonners** [comment]
the problem is that the matrix in SolvePressureCorrection becomes singular. An error message should be added with a suggestion to change either NX or STR3 in bou.in. A more general solution is not yet available.

**Comment by stevensrjam** [comment]
Added the error messages in the code. Commit 293.
